# Generated by Django 4.1.3 on 2022-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('not active', 'not active')], default='active', max_length=12, null=True),
        ),
    ]
